Repository iOS-vk-education/2023_1_iSnoops, pull requests merged in 2023-12, with the labels that each got.

#5 UI grigoriy
  README.md
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  easyLanguage/Application/AppDelegate.swift
  easyLanguage/Application/SceneDelegate.swift
  easyLanguage/Catalog/CatalogModel.swift
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
  easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegate.swift
  easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegateFlowLayout.swift
  easyLanguage/Catalog/Models/CategoryModel.swift
  easyLanguage/Catalog/Models/CategoryUIModel.swift
  easyLanguage/Catalog/Models/TopFiveWordsModel.swift
  easyLanguage/Catalog/Network/ApiModel/CategoryApiModel.swift
  easyLanguage/Catalog/Network/ApiModel/TopFiveWordsApiModel.swift
  easyLanguage/Catalog/Network/MockData.swift
  easyLanguage/Catalog/Network/Services/CatalogNetworkManager.swift
  easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
  easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
  easyLanguage/Catalog/Subviews/CollectionViews/CategoriesCollectionView.swift
  easyLanguage/Catalog/Subviews/CollectionViews/TopFiveCollectionView.swift
  easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
  easyLanguage/Catalog/Subviews/Views/ProgressView.swift
  easyLanguage/Catalog/Subviews/Views/TopFiveView.swift
  easyLanguage/Network/Managers/ImageManager.swift
  easyLanguage/Resources/Assets.xcassets/AddIconImage.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/AddIconImage.imageset/plus 1.png
  easyLanguage/Resources/Assets.xcassets/AddIconImage.imageset/plus 2.png
  easyLanguage/Resources/Assets.xcassets/AddIconImage.imageset/plus 3.png
  easyLanguage/Resources/Assets.xcassets/SortIconImage.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/SortIconImage.imageset/list-2 1.png
  easyLanguage/Resources/Assets.xcassets/SortIconImage.imageset/list-2 2.png
  easyLanguage/Resources/Assets.xcassets/SortIconImage.imageset/list-2.png
  easyLanguage/Resources/Assets.xcassets/plus-signIconImage.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/plus-signIconImage.imageset/plus-sign 1.png
  easyLanguage/Resources/Assets.xcassets/plus-signIconImage.imageset/plus-sign 2.png
  easyLanguage/Resources/Assets.xcassets/plus-signIconImage.imageset/plus-sign.png
  easyLanguage/TabBar/TabBarController.swift
  easyLanguage/UI/Color/Color + configurations.swift
  easyLanguage/UI/Color/Color + init.swift
  easyLanguage/UI/Color/Color.swift
  easyLanguage/UI/Color/ColorModeManager.swift
  easyLanguage/UI/Color/UIColor + configurations.swift
  easyLanguage/UI/CustomViewController/CustomViewController.swift
  easyLanguage/UI/Font/Font.swift
  easyLanguage/Words/WordsModel.swift
  easyLanguage/Words/WordsViewContoller.swift
Labels: Ждет апрува

#10 new models and mockData
  easyLanguage/Catalog/Subviews/Categories/CategoryUIModel.swift
  easyLanguage/Network/ApiModels/CategoryApiModel.swift
  easyLanguage/Network/ApiModels/TopFiveWordsApiModel.swift
  easyLanguage/Network/ApiModels/WordApiModel.swift
  easyLanguage/Network/Errors/ImageManagerErrors.swift
  easyLanguage/Network/Errors/NetworkErrors.swift
  easyLanguage/Network/Managers/ImageManager.swift
  easyLanguage/Network/MockData.swift
  easyLanguage/Network/Models/CategoryModel.swift
  easyLanguage/Network/Models/TopFiveWordsModel.swift
  easyLanguage/Network/Models/WordModel.swift
Labels: Ждет апрува, Ждет исправлений

#17 modified mockData and added uiModels
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/Network/MockData.swift
  easyLanguage/Network/UIModels/CategoryUIModel.swift
  easyLanguage/Network/UIModels/WordUIModel.swift
Labels: На проверке

#11 added code in tabBar and imagePicker, updated code in color
  easyLanguage/Application/SceneDelegate.swift
  easyLanguage/TabBar/TabBarController.swift
  easyLanguage/UI/Color/Color + configurations.swift
  easyLanguage/UI/Color/Color + extensions.swift
  easyLanguage/UI/CustomViewController/CustomViewController.swift
  easyLanguage/UI/ImagePicker/ImagePicker.swift
Labels: Ждет апрува

#19 edited tabbar item config
  easyLanguage/TabBar/TabBarController.swift
Labels: Ждет апрува

#15 Add LearningVC
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  easyLanguage/LearningView/LearningViewController.swift
  easyLanguage/TabBar/TabBarController.swift
Labels: Ждет апрува

#23 modified progressView
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/UI/View/ProgressView.swift
Labels: Ждет апрува

#25 New VC with categories inside CatalogVC
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/Catalog/CatalogModel.swift
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
  easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegate.swift
  easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegateFlowLayout.swift
  easyLanguage/Catalog/Subviews/Categories/CategoriesView.swift
  easyLanguage/Categories/CategoriesModel.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/Categories/Delegates/CategoriesCollectionViewDataSource.swift
  easyLanguage/Categories/Delegates/CategoriesCollectionViewDelegate.swift
  easyLanguage/Categories/Delegates/CategoriesCollectionViewDelegateFlowLayout.swift
  easyLanguage/Categories/Subviews/CategoriesCollectionView.swift
  easyLanguage/Categories/Subviews/CategoryCollectionViewCell.swift
Labels: Ждет апрува

#27 added Firebase
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  easyLanguage/Application/AppDelegate.swift
  easyLanguage/Resources/GoogleService-Info.plist
Labels: Ждет апрува

#29 edited FB files
  easyLanguage.xcodeproj/project.pbxproj
Labels: Ждет апрува

#12 Add new category (BottomSheet)
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage.xcodeproj/xcshareddata/xcschemes/easyLanguage.xcscheme
  easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
  easyLanguage/Catalog/Subviews/TopFive/TopFiveView.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/UI/Color/Color + configurations.swift
Labels: Ждет апрува

#32 added fonts in CatalogVC
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Catalog/Subviews/TopFive/TopFiveCollectionViewCell.swift
  easyLanguage/Catalog/Subviews/TopFive/TopFiveView.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/Categories/Subviews/CategoryCollectionViewCell.swift
  easyLanguage/UI/Font/Font.swift
  easyLanguage/UI/View/ProgressView.swift
Labels: Ждет апрува

#20 Add new word (BottomSheet)
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  easyLanguage/AddNewWord/AddNewWordViewController.swift
Labels: Ждет апрува

#33 edited topFiveView, in collection added insetForSectionAt, removed un…
  easyLanguage.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegateFlowLayout.swift
  easyLanguage/Catalog/Subviews/TopFive/TopFiveView.swift
Labels: Ждет апрува

#34 added localization on CatalogVC
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Catalog/Subviews/TopFive/TopFiveView.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/LearningView/LearningViewController.swift
  easyLanguage/TabBar/TabBarController.swift
  easyLanguage/UI/View/ProgressView.swift
  easyLanguage/en.lproj/Localizable.strings
  easyLanguage/ru.lproj/Localizable.strings
Labels: Ждет апрува

#21 added VC CategoryDetail
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/CategoryDetail/CategoryDetailModel.swift
  easyLanguage/CategoryDetail/CategoryDetailViewController.swift
  easyLanguage/CategoryDetail/Delegates/CategoryDetailCollectionViewDataSource.swift
  easyLanguage/CategoryDetail/Delegates/CategoryDetailCollectionViewDelegate.swift
  easyLanguage/CategoryDetail/Delegates/CategoryDetailCollectionViewDelegateFlowLayout.swift
  easyLanguage/CategoryDetail/Services/CategoryDetailNetworkManager.swift
  easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionView.swift
  easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
  easyLanguage/Resources/Assets.xcassets/Star.fill.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/Star.fill.imageset/star.fill 1.svg
  easyLanguage/Resources/Assets.xcassets/Star.fill.imageset/star.fill 2.svg
  easyLanguage/Resources/Assets.xcassets/Star.fill.imageset/star.fill.svg
  easyLanguage/Resources/Assets.xcassets/Star.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/Star.imageset/star 1.svg
  easyLanguage/Resources/Assets.xcassets/Star.imageset/star 2.svg
  easyLanguage/Resources/Assets.xcassets/Star.imageset/star 3.svg
Labels: На проверке

#36 added id to word
  easyLanguage/CategoryDetail/CategoryDetailModel.swift
  easyLanguage/CategoryDetail/CategoryDetailViewController.swift
  easyLanguage/Network/ApiModels/WordApiModel.swift
  easyLanguage/Network/MockData.swift
  easyLanguage/Network/UIModels/WordUIModel.swift
Labels: На проверке

#31 added data from FireBase
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Catalog/Services/CategoryService.swift
  easyLanguage/Categories/CategoriesViewController.swift
Labels: Ждет исправлений

#37 Onboarding without pictures
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/AddNewWord/AddNewWordViewController.swift
  easyLanguage/Application/SceneDelegate.swift
  easyLanguage/Onboarding/OnboardingCollectionViewCell.swift
  easyLanguage/Onboarding/OnboardingViewController.swift
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
Labels: Ждет апрува

#40 removed level in top 5 words
  easyLanguage/Catalog/CatalogModel.swift
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Catalog/Subviews/TopFive/TopFiveCollectionViewCell.swift
  easyLanguage/Network/ApiModels/TopFiveWordsApiModel.swift
  easyLanguage/Network/MockData.swift
  easyLanguage/Network/Models/TopFiveWordsModel.swift
Labels: Ждет апрува

#28 added sort
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Categories/CategoriesModel.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/Categories/Subviews/CategoryCollectionViewCell.swift
  easyLanguage/Network/Models/CategoryModel.swift
  easyLanguage/Network/UIModels/CategoryUIModel.swift
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
Labels: На проверке

#39 added logic in CategoryDetail
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/AddNewWord/AddNewWordModel.swift
  easyLanguage/AddNewWord/AddNewWordService.swift
  easyLanguage/AddNewWord/AddNewWordViewController.swift
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Categories/CategoriesModel.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/Categories/Delegates/CategoriesCollectionViewDataSource.swift
  easyLanguage/Categories/Subviews/CategoriesCollectionView.swift
  easyLanguage/CategoryDetail/CategoryDetailModel.swift
  easyLanguage/CategoryDetail/CategoryDetailService.swift
  easyLanguage/CategoryDetail/CategoryDetailViewController.swift
  easyLanguage/CategoryDetail/Delegates/CategoryDetailCollectionViewDataSource.swift
  easyLanguage/CategoryDetail/Services/CategoryDetailNetworkManager.swift
  easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
  easyLanguage/Network/MockData.swift
  easyLanguage/Network/UIModels/WordUIModel.swift
  easyLanguage/Onboarding/OnboardingCollectionViewCell.swift
  easyLanguage/Onboarding/OnboardingViewController.swift
Labels: Ждет апрува

#41 removed bug in categorydetail colors after sorting
  easyLanguage/Categories/Delegates/CategoriesCollectionViewDataSource.swift
  easyLanguage/CategoryDetail/CategoryDetailViewController.swift
Labels: На проверке

#16 added services
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/Catalog/CatalogModel.swift
  easyLanguage/Catalog/Services/TopFiveService.swift
  easyLanguage/Catalog/Services/WordsService.swift
  easyLanguage/Categories/CategoriesModel.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/Categories/CategoryService.swift
Labels: Ждет апрува

#42 added topFiveService (added FB)
  easyLanguage/Catalog/CatalogModel.swift
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Catalog/Services/TopFiveService.swift
  easyLanguage/Catalog/Subviews/TopFive/TopFiveView.swift
Labels: Ждет апрува

#8 Profile chistyakov
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
  easyLanguage/Application/AppDelegate.swift
  easyLanguage/Application/SceneDelegate.swift
  easyLanguage/Auth/AlertManager.swift
  easyLanguage/Auth/AuthService.swift
  easyLanguage/Auth/Register+LoginUserRequestModel.swift
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Catalog/Services/TopFiveService.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/CategoryDetail/CategoryDetailViewController.swift
  easyLanguage/Network/ApiModels/ProfileApiModel.swift
  easyLanguage/Network/MockData.swift
  easyLanguage/Onboarding/OnboardingCollectionViewCell.swift
  easyLanguage/Onboarding/OnboardingViewController.swift
  easyLanguage/Profile/ProfileModel.swift
  easyLanguage/Profile/ProfileService.swift
  easyLanguage/Profile/ProfileViewController.swift
  easyLanguage/Profile/Subviews/ChoosingThemeView.swift
  easyLanguage/Profile/Subviews/UserInformationView.swift
  easyLanguage/Resources/Assets.xcassets/Onboarding_1.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/Onboarding_1.imageset/Onboarding_1.png
  easyLanguage/Resources/Assets.xcassets/Onboarding_1.imageset/Onboarding_1@2x.png
  easyLanguage/Resources/Assets.xcassets/Onboarding_1.imageset/Onboarding_1@3x.png
  easyLanguage/Resources/Assets.xcassets/Onboarding_2.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/Onboarding_2.imageset/Onboarding_2.png
  easyLanguage/Resources/Assets.xcassets/Onboarding_2.imageset/Onboarding_2@2x.png
  easyLanguage/Resources/Assets.xcassets/Onboarding_2.imageset/Onboarding_2@3x.png
  easyLanguage/Resources/Assets.xcassets/Onboarding_3.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/Onboarding_3.imageset/Onboarding_3.png
  easyLanguage/Resources/Assets.xcassets/Onboarding_3.imageset/Onboarding_3@2x.png
  easyLanguage/Resources/Assets.xcassets/Onboarding_3.imageset/Onboarding_3@3x.png
  easyLanguage/Resources/Assets.xcassets/ProfileEmptyImage.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/ProfileEmptyImage.imageset/image 80.png
  easyLanguage/Resources/Assets.xcassets/ProfileEmptyImage.imageset/image 81.png
  easyLanguage/Resources/Assets.xcassets/ProfileEmptyImage.imageset/image 82.png
  easyLanguage/Resources/Base.lproj/LaunchScreen.storyboard
  easyLanguage/Resources/Info.plist
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
  easyLanguage/TabBar/TabBarController.swift
  easyLanguage/UI/Color/Color + configurations.swift
  easyLanguage/UI/Color/ColorModeManager.swift
  easyLanguage/UI/Font/Font.swift
Labels: Ждет апрува
