Repository iOS-vk-education/2023_1_iSnoops, pull requests merged in 2024-05, with the labels that each got.

#73 Bugfix/concurency/profile
  easyLanguage/Profile/Subviews/UserInformationView.swift
Labels: Ждет апрува

#78 Async profile
  easyLanguage.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  easyLanguage/Profile/ProfileModel.swift
  easyLanguage/Profile/ProfileService.swift
  easyLanguage/Profile/ProfileViewController.swift
  easyLanguage/Profile/Subviews/UserInformationView.swift
Labels: Ждет апрува

#74 Feature/pushes
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
  easyLanguage/Application/AppDelegate.swift
  easyLanguage/Application/SceneDelegate.swift
  easyLanguage/Auth/Views/RegistrationViewController.swift
  easyLanguage/PushManager/PushManager.swift
  easyLanguage/PushManager/PushStatus.swift
  easyLanguage/easyLanguage.entitlements
  push.apns
Labels: Ждет апрува

#79 Захардкоженный экран ачивок + база для экрана ачивок/статистики
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
  easyLanguage/Achievements/AchievementViewController.swift
  easyLanguage/Profile/ProfileService.swift
  easyLanguage/Profile/ProfileViewController.swift
  easyLanguage/Resources/Assets.xcassets/AchievementCompletionIcon.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/AchievementCompletionIcon.imageset/Group 1167.png
  easyLanguage/Resources/Assets.xcassets/AchievementCompletionIcon.imageset/Group 1168.png
  easyLanguage/Resources/Assets.xcassets/AchievementCompletionIcon.imageset/Group 1169.png
  easyLanguage/Resources/Assets.xcassets/AchievementNotDone.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/AchievementNotDone.imageset/Group 1187.png
  easyLanguage/Resources/Assets.xcassets/AchievementNotDone.imageset/Group 1188.png
  easyLanguage/Resources/Assets.xcassets/AchievementNotDone.imageset/Group 1189.png
  easyLanguage/Resources/Assets.xcassets/AchievementsImageMock.imageset/37b14ac47d7111ee95122aa0df1cd6e5-upscaled 1.jpeg
  easyLanguage/Resources/Assets.xcassets/AchievementsImageMock.imageset/37b14ac47d7111ee95122aa0df1cd6e5-upscaled 2.jpeg
  easyLanguage/Resources/Assets.xcassets/AchievementsImageMock.imageset/37b14ac47d7111ee95122aa0df1cd6e5-upscaled.jpeg
  easyLanguage/Resources/Assets.xcassets/AchievementsImageMock.imageset/Contents.json
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
  easyLanguage/TabBar/TabBarController.swift
  easyLanguage/UI/Color/Color + configurations.swift
  easyLanguage/UI/Color/ColorModeManager.swift
Labels: Ждет апрува

#75 add StatisticView
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
  easyLanguage/AddWord/Interactor/AddWordService.swift
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
  easyLanguage/Statistic/Charts/CategoriesWordsChart.swift
  easyLanguage/Statistic/Charts/PieBar.swift
  easyLanguage/Statistic/StatisticModel.swift
  easyLanguage/Statistic/StatisticService.swift
  easyLanguage/Statistic/StatisticVIew.swift
  easyLanguage/Statistic/StatisticViewModel.swift
Labels: Ждет апрува

#83 изменен launch
  easyLanguage/Resources/Assets.xcassets/Launch.imageset/360_F_125806127_4le86CYCwHiBXOtpKDPXaZYzMEjoJVFD 1.jpg
  easyLanguage/Resources/Assets.xcassets/Launch.imageset/360_F_125806127_4le86CYCwHiBXOtpKDPXaZYzMEjoJVFD 2.jpg
  easyLanguage/Resources/Assets.xcassets/Launch.imageset/360_F_125806127_4le86CYCwHiBXOtpKDPXaZYzMEjoJVFD.jpg
  easyLanguage/Resources/Assets.xcassets/Launch.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/icon.imageset/AppIcon1024x1024 1.png
  easyLanguage/Resources/Assets.xcassets/icon.imageset/AppIcon1024x1024 2.png
  easyLanguage/Resources/Assets.xcassets/icon.imageset/AppIcon1024x1024.png
  easyLanguage/Resources/Assets.xcassets/icon.imageset/Contents.json
  easyLanguage/Resources/Base.lproj/LaunchScreen.storyboard
Labels: Ждет апрува

#77 добавлен враппер на добавление категории
  easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
Labels: Ждет апрува

#80 Feature/core data on learning view
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/AddWord/Interactor/AddWordService.swift
  easyLanguage/Application/AppDelegate.swift
  easyLanguage/CoreData/CdModel.xcdatamodeld/Model.xcdatamodel/contents
  easyLanguage/CoreData/CoreDataService.swift
  easyLanguage/CoreData/WordCDModel+CoreDataClass.swift
  easyLanguage/CoreData/WordCDModel+CoreDataProperties.swift
  easyLanguage/LearningView/LearningViewController.swift
  easyLanguage/LearningView/LearningViewModel.swift
Labels: Ждет апрува

#76 добавлены категории/слова/топ5 по умолчанию при создании регистрации …
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/AddNewCategory/AddNewCategoryService.swift
  easyLanguage/AddWord/Interactor/AddWordService.swift
  easyLanguage/Auth/Views/RegistrationViewController.swift
  easyLanguage/Catalog/CatalogViewController.swift
  easyLanguage/Catalog/Services/TopFiveService.swift
  easyLanguage/LearningView/LearningViewService.swift
  easyLanguage/Network/DefaultData.swift
  easyLanguage/Network/MockData.swift
  easyLanguage/Profile/ProfileModel.swift
  easyLanguage/Profile/ProfileViewController.swift
  easyLanguage/TabBar/TabBarController.swift
  easyLanguage/UI/Color/Color + configurations.swift
  easyLanguage/UI/Color/ColorModeManager.swift
Labels: Ждет исправлений

#71 Feature/learn category
  easyLanguage/AddWord/Interactor/AddWordInteractor.swift
  easyLanguage/AddWord/ViewController/AddWordViewController.swift
  easyLanguage/CategoryDetail/CategoryDetailViewController.swift
  easyLanguage/CategoryDetail/Delegates/CategoryDetailCollectionViewDelegateFlowLayout.swift
  easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionView.swift
  easyLanguage/LearningView/LearningViewController.swift
  easyLanguage/LearningView/LearningViewModel.swift
  easyLanguage/LearningView/LearningViewService.swift
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
Labels: Готов к мержу с мастером

#72 Feature/delete category
  easyLanguage/Categories/CategoriesModel.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/Categories/CategoryService.swift
  easyLanguage/Categories/Delegates/CategoriesCollectionViewDataSource.swift
  easyLanguage/Categories/Subviews/CategoryCollectionViewCell.swift
  easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
Labels: Готов к мержу с мастером

#85 Bugfix/title of sort
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
Labels: Готов к мержу с мастером

#89 добавлена локализация
  easyLanguage/AddWord/ViewController/AddWordViewController.swift
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
Labels: Готов к мержу с мастером

#88 добавлена проверка
  easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
  easyLanguage/Auth/AlertManager.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
Labels: Готов к мержу с мастером

#90 исправлен баг
  easyLanguage/Application/SceneDelegate.swift
  easyLanguage/Auth/Views/RegistrationViewController.swift
  easyLanguage/Catalog/Network/ApiModels/TranslationApiModel.swift
Labels: Готов к мержу с мастером

#92 Fix bug with registrationButton
  easyLanguage/AddWord/Interactor/AddWordService.swift
  easyLanguage/Auth/Views/RegistrationViewController.swift
Labels: Готов к мержу с мастером

#81 Добавлен сетевой слой для экрана достижений
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  easyLanguage/Achievements/AchievementManager.swift
  easyLanguage/Achievements/AchievementModels/AchievementEntityModel.swift
  easyLanguage/Achievements/AchievementModels/AchievementModel.swift
  easyLanguage/Achievements/AchievementStaticsBaseView.swift
  easyLanguage/Achievements/AchievementView.swift
  easyLanguage/Achievements/AchievementViewController.swift
  easyLanguage/AddNewCategory/AddNewCategoryService.swift
  easyLanguage/AddWord/Interactor/AddWordService.swift
  easyLanguage/Categories/CategoriesModel.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/CategoryDetail/CategoryDetailService.swift
  easyLanguage/Network/ApiModels/CategoryApiModel.swift
  easyLanguage/Network/DefaultData.swift
  easyLanguage/Network/Models/CategoryModel.swift
  easyLanguage/Profile/ProfileViewController.swift
  easyLanguage/Resources/Assets.xcassets/AchievementDone.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/AchievementDone.imageset/Group 1167.png
  easyLanguage/Resources/Assets.xcassets/AchievementDone.imageset/Group 1168.png
  easyLanguage/Resources/Assets.xcassets/AchievementDone.imageset/Group 1169.png
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
  easyLanguage/TabBar/TabBarController.swift
Labels: Ждет исправлений

#96 редизайн
  easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
  easyLanguage/Resources/Assets.xcassets/bookmark.fill.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/bookmark.fill.imageset/bookmark.fill 1.svg
  easyLanguage/Resources/Assets.xcassets/bookmark.fill.imageset/bookmark.fill 2.svg
  easyLanguage/Resources/Assets.xcassets/bookmark.fill.imageset/bookmark.fill.svg
  easyLanguage/Resources/Assets.xcassets/bookmark.imageset/Contents.json
  easyLanguage/Resources/Assets.xcassets/bookmark.imageset/bookmark 1.svg
  easyLanguage/Resources/Assets.xcassets/bookmark.imageset/bookmark 2.svg
  easyLanguage/Resources/Assets.xcassets/bookmark.imageset/bookmark.svg
Labels: Готов к мержу с мастером

#98 изменена логика пушей. При создании первой категории в новом аккаунте…
  easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
  easyLanguage/Application/AppDelegate.swift
  easyLanguage/Application/SceneDelegate.swift
  easyLanguage/Auth/Views/RegistrationViewController.swift
  easyLanguage/Extentions/String + ext.swift
  easyLanguage/Profile/ProfileViewController.swift
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
Labels: Готов к мержу с мастером

#99 добавлен класс, отслеживающий инет
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/Network/NetworkMonitor/NetworkMonitor.swift
Labels: На проверке

#100 добавлена кор дата для списка слов
  easyLanguage/CategoryDetail/CategoryDetailModel.swift
  easyLanguage/CategoryDetail/CategoryDetailService.swift
  easyLanguage/CategoryDetail/CategoryDetailViewController.swift
  easyLanguage/CoreData/CoreDataService.swift
  easyLanguage/LearningView/LearningViewController.swift
  easyLanguage/LearningView/LearningViewModel.swift
Labels: На проверке

#97 добавлены дефолтные категории в кор дату + рефакторинг (в сцене navig…
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
  easyLanguage/Application/SceneDelegate.swift
  easyLanguage/Auth/Views/RegistrationViewController.swift
  easyLanguage/Categories/CategoriesViewController.swift
  easyLanguage/CoreData/CategoryCDModel+CoreDataClass.swift
  easyLanguage/CoreData/CategoryCDModel+CoreDataProperties.swift
  easyLanguage/CoreData/CdModel.xcdatamodeld/Model.xcdatamodel/contents
  easyLanguage/CoreData/CoreDataService.swift
Labels: На проверке

#103 Feature/new learning vc
  easyLanguage.xcodeproj/project.pbxproj
  easyLanguage/LearningView/LearningCardView.swift
  easyLanguage/LearningView/LearningViewController.swift
  easyLanguage/Resources/en.lproj/Localizable.strings
  easyLanguage/Resources/ru.lproj/Localizable.strings
Labels: Ждет апрува
